if GetLocale() ~= "ukUK" then return end

--- New Proshlyapation Ochka Murchalya Proshlyapenko? ---

DBM_CORE_NEED_SUPPORT				= "Ви - програміст або хороший перекладач? Якщо так, то нам потрібна ваша допомога в локалізації DBM іншими мовами. Допоможіть нам, відвідавши |HDBM:forums|h|cff3588ffhttps://github.com/Aleksart163/DBM-RV|r.\nЗнайшли баг або неправильний таймер? Ви вважаєте, що якомусь модулю потрібне додаткове попередження, таймер або особливість?\nВідвідайте нові форуми DBM для обговорень, повідомлень про помилки та запиту нових можливостей на " .. DBM_CORE_UPDATEREMINDER_URL .. "."
DBM_HOW_TO_USE_MOD					= "Ласкаво просимо в DBM. Для доступу до налаштувань наберіть /dbm у чаті. За бажання, завантажте певні зони вручну для змін специфічних налаштувань для кожного боса. DBM намагається підлаштовуватися під вас на основі вашої спеціалізації на момент першого запуску, але деякі можуть захотіти ввімкнути додаткові опції."
DBM_FORUMS_MESSAGE					= "Знайшли баг або неправильний таймер? Вважаєте, що якомусь модулю потрібне додаткове попередження, таймер, особливість або локалізація? \nЗ усіма питаннями можете звертатися на discord Aleksart163, /w Куплиняшка або залишати запити на |h|cff3588ffhttps://github.com/Aleksart163/DBM-RV/pulls|r"
DBM_SILENT_REMINDER					= "Напоминание: DBM все еще находится в беззвучном режиме."

DBM_CORE_LOAD_MOD_ERROR				= "Помилка під час завантаження бос модуля для %s: %s"
DBM_CORE_LOAD_MOD_SUCCESS			= "Завантажено модуль для '%s'. Для додаткових налаштувань введіть /dbm або /dbm help у чаті."
DBM_CORE_LOAD_MOD_COMBAT			= "Завантаження '%s' відкладено до виходу з бою"
DBM_CORE_LOAD_GUI_ERROR				= "Не вдалося завантажити GUI: %s"
DBM_CORE_LOAD_GUI_COMBAT			= "GUI не може бути спочатку завантажено в бою. GUI буде завантажено після бою. Після завантаження GUI ви зможете завантажувати його в бою."
DBM_CORE_BAD_LOAD					= "DBM не вдалося повністю завантажити модуль для цього підземелля, оскільки ви перебуваєте в режимі бою. Щойно ви вийдете з бою, будь ласка, зробіть /console reloadui якомога швидше."
DBM_CORE_LOAD_MOD_VER_MISMATCH		= "%s не може бути завантажений тому що ваш DBM-Core не відповідає вимогам. Потрібна оновлена версія."
DBM_CORE_LOAD_MOD_EXP_MISMATCH		= "%s не може бути завантажений, тому що він призначений для розширення WoW, яке наразі недоступне. Коли нове розширення стане доступним, цей мод працюватиме автоматично."
DBM_CORE_LOAD_MOD_DISABLED			= "%s встановлено, але наразі вимкнено. Цей мод не буде завантажено, поки ви не ввімкнете його."
DBM_CORE_LOAD_MOD_DISABLED_PLURAL	= "%s встановлені, але наразі вимкнені. Ці моди не завантажуватимуться, доки ви не ввімкнете їх."

DBM_CORE_UPDATEREMINDER_URL			= "https://github.com/Aleksart163/DBM-RV"

DBM_COPY_URL_DIALOG					= "Відвідайте наш сайт для оновлення на останню версію аддона."

--Pre Patch 7.1 Notice
DBM_CORE_NO_RANGE_SOON				= "Увага: радар буде недоступний у підземеллях у патчі 7.1"
--Post Patch 7.1
DBM_CORE_NO_RANGE					= "Радар не може бути використаний у підземеллях. Буде використовуватися текстове вікно перевірки дистанції."
DBM_CORE_NO_ARROW					= "Стрілка не може бути використана в підземеллях."
DBM_CORE_ARROW_SUMMONED				= "Стрілку було активовано. Якщо ви не зробили це вручну, то для активації стрілки у вас налаштований аддон стороннього виробника."
DBM_CORE_NO_HUD						= "HUDMap не може бути використана в підземеллях."

DBM_CORE_DYNAMIC_DIFFICULTY_CLUMP	= "DBM відключив динамічне вікно перевірки дистанції на цьому босі, тому що немає точної інформації про необхідну кількість гравців в одному скупченні для рейду вашого розміру."
DBM_CORE_DYNAMIC_ADD_COUNT			= "DBM відключив попередження про появу помічників на цьому босі, тому що немає точної інформації про кількість помічників, які з'являються в рейді вашого розміру."
DBM_CORE_DYNAMIC_MULTIPLE			= "DBM відключив кілька таймерів і попереджень на цьому босі, тому що немає точної інформації про те, як працюють механіки енкаунтера для рейду вашого розміру."

DBM_CORE_LOOT_SPEC_REMINDER			= "Ваша поточна спеціалізація %s. Ви вибрали здобич для спеціалізації %s."

DBM_CORE_BIGWIGS_ICON_CONFLICT		= "DBM виявив, що у вас увімкнено встановлення міток у BigWigs і DBM одночасно. Будь ласка, вимкніть мітки в одному з них, щоб уникнути конфлікту з лідером вашої групи."

DBM_CORE_MOD_AVAILABLE				= "Для цього контенту доступний додатковий модуль %s. Ви можете завантажити його з |HDBM:forums|h|cff3588ffhttps://github.com/Aleksart163/DBM-RV|r. Це повідомлення відображається один раз."

DBM_CORE_COMBAT_STARTED				= "%s вступає в бій. Удачі! :)"
DBM_CORE_COMBAT_STARTED_IN_PROGRESS	= "%s вступає в бій (у процесі). Удачі! :)"
DBM_CORE_GUILD_COMBAT_STARTED		= "Гільдія вступає в бій із %s"
DBM_CORE_SCENARIO_STARTED			= "%s розпочато. Удачі! :)"
DBM_CORE_SCENARIO_STARTED_IN_PROGRESS	= "Ви зайшли в сценарій %s (у процесі). Удачі! :)"
DBM_CORE_BOSS_DOWN					= "%s гине через %s!"
DBM_CORE_BOSS_DOWN_I				= "%s гине! Загальна кількість перемог у Вас %d."
DBM_CORE_BOSS_DOWN_L				= "%s гине через %s! Ваш останній бій тривав %s, а найкращий бій тривав %s. Загальна кількість перемог у Вас %d."
DBM_CORE_BOSS_DOWN_NR				= "%s гине через %s! Це новий рекорд! (Попередній рекорд був %s). Загальна кількість перемог у Вас %d."
DBM_CORE_GUILD_BOSS_DOWN			= "Гільдія перемогла %s через %s!"
DBM_CORE_SCENARIO_COMPLETE			= "%s завершено через %s!"
DBM_CORE_SCENARIO_COMPLETE_I		= "%s завершено! Загальна кількість проходжень у Вас %d."
DBM_CORE_SCENARIO_COMPLETE_L		= "%s завершено через %s! Ваше останнє проходження зайняло %s, а найкраще проходження зайняло %s. Загальна кількість проходжень у Вас %d."
DBM_CORE_SCENARIO_COMPLETE_NR		= "%s завершено через %s! Це новий рекорд! (Попередній рекорд був %s). Загальна кількість проходжень у Вас %d."
DBM_CORE_COMBAT_ENDED_AT			= "Бій із %s (%s) закінчився через %s."
DBM_CORE_COMBAT_ENDED_AT_LONG		= "Бій із %s (%s) закінчився через %s. На цьому рівні складності ви вайпнулися вже %d разів."
DBM_CORE_GUILD_COMBAT_ENDED_AT		= "Гільдія вайпнулася на %s (%s) через %s."
DBM_CORE_SCENARIO_ENDED_AT			= "%s закінчився через %s."
DBM_CORE_SCENARIO_ENDED_AT_LONG		= "%s закінчився через %s. На цьому рівні складності ви не завершили сценарій уже %d разів."
DBM_CORE_COMBAT_STATE_RECOVERED		= "%s було атаковано %s тому, відновлюю таймери..."
DBM_CORE_TRANSCRIPTOR_LOG_START		= "Логування за допомогою Transcriptor розпочато."
DBM_CORE_TRANSCRIPTOR_LOG_END		= "Логування за допомогою Transcriptor закінчено."

DBM_CORE_MOVIE_SKIPPED				= "Ролик був автоматично пропущений."

DBM_CORE_AFK_WARNING				= "Ви АФК і перебуваєте в бою (залишилося %d відсотків здоров'я), звукове сповіщення про бій. Якщо ви не АФК, зніміть прапор АФК або вимкніть цю опцію в \"додаткових можливостях\"."

DBM_CORE_COMBAT_STARTED_AI_TIMER	= "Мій процесор - це процесор нейронної мережі; самонавчальний комп'ютер. (У цьому бою буде використовуватися нова функція ШІ таймера для генерації наближених значень таймера)."
--
DBM_CORE_PROFILE_NOT_FOUND			= "<DBM RV> Ваш поточний профіль пошкоджено. DBM завантажить профіль 'За замовчуванням'."
DBM_CORE_PROFILE_CREATED			= "Профіль '%s' створено."
DBM_CORE_PROFILE_CREATE_ERROR		= "Не вдалося створити профіль. Некоректне ім'я профілю."
DBM_CORE_PROFILE_CREATE_ERROR_D		= "Не вдалося створити профіль. Профіль '%s' уже існує."
DBM_CORE_PROFILE_APPLIED			= "Профіль '%s' застосовано."
DBM_CORE_PROFILE_APPLY_ERROR		= "Не вдалося застосувати профіль. Профіль '%s' не існує."
DBM_CORE_PROFILE_COPIED				= "Профіль '%s' скопійовано."
DBM_CORE_PROFILE_COPY_ERROR			= "Не вдалося скопіювати профіль. Профіль '%s' не існує."
DBM_CORE_PROFILE_COPY_ERROR_SELF	= "Неможливо скопіювати профіль сам у себе."
DBM_CORE_PROFILE_DELETED			= "Профіль '%s' видалено. Профіль 'За замовчуванням' буде застосовано."
DBM_CORE_PROFILE_DELETE_ERROR		= "Не вдалося видалити профіль. Профіль '%s' не існує."
DBM_CORE_PROFILE_CANNOT_DELETE		= "Неможливо видалити профіль 'За замовчуванням'."
DBM_CORE_MPROFILE_COPY_SUCCESS		= "Налаштування модуля від %s (спеціалізація %d) було скопійовано."
DBM_CORE_MPROFILE_COPY_SELF_ERROR	= "Неможливо скопіювати налаштування персонажа самі в себе."
DBM_CORE_MPROFILE_COPY_S_ERROR		= "Джерело пошкоджено. Налаштування не скопійовано або скопійовано частково. Скопіювати не вдалося."
DBM_CORE_MPROFILE_COPYS_SUCCESS		= "Звукові налаштування модуля від %s (спеціалізація %d) було скопійовано."
DBM_CORE_MPROFILE_COPYS_SELF_ERROR	= "Неможливо скопіювати звукові налаштування персонажа самі в себе."
DBM_CORE_MPROFILE_COPYS_S_ERROR		= "Джерело пошкоджено. Звукові налаштування не скопійовано або скопійовано частково. Скопіювати не вдалося."
DBM_CORE_MPROFILE_DELETE_SUCCESS	= "Налаштування модуля від %s (спеціалізація %d) було видалено."
DBM_CORE_MPROFILE_DELETE_SELF_ERROR	= "Неможливо видалити налаштування модуля, який використовується на даний момент."
DBM_CORE_MPROFILE_DELETE_S_ERROR	= "Джерело пошкоджено. Налаштування не видалено або видалено частково. Видалити не вдалося."

DBM_CORE_NOTE_SHARE_SUCCESS			= "%s поділився своєю заміткою для %s."
DBM_CORE_NOTE_SHARE_FAIL			= "%s спробував поділитися з вами заміткою для %s. Однак модуль, пов'язаний із цією здатністю, не встановлено або не завантажено. Якщо вам потрібна ця замітка, переконайтеся, що модуль, для якого вони діляться заміткою, завантажений, і попросіть поділитися знову."

DBM_CORE_NOTEHEADER					= "Вставте текст вашої замітки тут. Помістивши ім'я гравця між >< забарвить його в колір класу. Для попереджень із кількома нотатками, розділіть нотатки за допомогою '/'"
DBM_CORE_NOTEFOOTER					= "Коли нотатка оновлена, просто натисніть 'ОК' щоб зберегти."
DBM_CORE_NOTESHAREDHEADER			= "%s поділився заміткою для %s. Якщо ви приймете її, вона перевизначить вашу поточну замітку."
DBM_CORE_NOTESHARED					= "Вашу замітку було надіслано групі."
DBM_CORE_NOTESHAREERRORSOLO			= "Самотньо? Ви не повинні передавати нотатки самому собі."
DBM_CORE_NOTESHAREERRORBLANK		= "Не можна поділитися порожньою заміткою."
DBM_CORE_NOTESHAREERRORGROUPFINDER	= "Не можна поділитися нотаткою на БГ, у пошуку рейду або підземелля."
DBM_CORE_NOTESHAREERRORALREADYOPEN	= "Не можна відкрити посилання нотатки, доки відкрито редактор нотаток, щоб запобігти втраті нотатки, яку ви в цей момент редагуєте."

DBM_CORE_ALLMOD_DEFAULT_LOADED		= "Налаштування за замовчуванням були завантажені для всіх модулів у цьому підземеллі."
DBM_CORE_ALLMOD_STATS_RESETED		= "Усю статистику модуля було скинуто."
DBM_CORE_MOD_DEFAULT_LOADED			= "Налаштування за замовчуванням для цього бою були завантажені."

DBM_CORE_WORLDBOSS_ENGAGED			= "У вашому ігровому світі, можливо, розпочався бій із %s (%s відсотків здоров'я, відправив %s)."
DBM_CORE_WORLDBOSS_DEFEATED			= "%s можливо був переможений у вашому ігровому світі (відправив %s)."

DBM_CORE_TIMER_FORMAT_SECS 			= "%.2f сек"
DBM_CORE_TIMER_FORMAT_MINS 			= "%d хв"
DBM_CORE_TIMER_FORMAT 				= "%d хв %.2f сек"

DBM_CORE_MIN 						= "хв"
DBM_CORE_MIN_FMT					= "%d хв"
DBM_CORE_SEC 						= "сек"
DBM_CORE_SEC_FMT 					= "%s сек"

DBM_CORE_GENERIC_WARNING_OTHERS 	= "і ще один"
DBM_CORE_GENERIC_WARNING_OTHERS2 	= "і %d інших"
DBM_CORE_GENERIC_WARNING_BERSERK 	= "Берсерк через %s %s."
DBM_CORE_GENERIC_TIMER_BERSERK 		= "Берсерк"
DBM_CORE_OPTION_TIMER_BERSERK 		= "Відлік часу до $spell:26662"
DBM_CORE_OPTION_TIMER_COMBAT 		= "Відлік часу до початку бою"
DBM_CORE_GENERIC_TIMER_COMBAT 		= "Бій почнеться через"
DBM_CORE_OPTION_TIMER_DOOR_OPENING 	= "Відлік часу до відкриття дверей"
DBM_CORE_GENERIC_TIMER_DOOR_OPENING = "Відчинення дверей"
DBM_CORE_GENERIC_TIMER_ROLE_PLAY 	= "Активувати рольові ігри або npc в 1 натискання"
DBM_CORE_BAD 						= "Поганий"

DBM_CORE_OPTION_CATEGORY_TIMERS 		= "Індикатори"
DBM_CORE_OPTION_CATEGORY_WARNINGS 		= "Загальні попередження"
DBM_CORE_OPTION_CATEGORY_WARNINGS_YOU 	= "Персональні попередження"
DBM_CORE_OPTION_CATEGORY_WARNINGS_OTHER = "Попередження для цілі"
DBM_CORE_OPTION_CATEGORY_WARNINGS_ROLE 	= "Попередження для ролі"
DBM_CORE_OPTION_CATEGORY_SOUNDS 		= "Звуки"
DBM_CORE_OPTION_CATEGORY_DROPDOWNS 		= "Випадаючі вікна"

DBM_CORE_AUTO_RESPONDED 			= "Авто-відповідь."
DBM_CORE_STATUS_WHISPER 			= "%s: %s, %d/%d людина жива"
--Bosses
DBM_CORE_AUTO_RESPOND_WHISPER 				= "%s зараз зайнятий, у бою проти %s (%s, %d/%d осіб живі)"
DBM_CORE_WHISPER_COMBAT_END_KILL 			= "%s здобув перемогу над %s!"
DBM_CORE_WHISPER_COMBAT_END_KILL_STATS 		= "%s здобув перемогу над %s! Загальна кількість перемог у них - %d."
DBM_CORE_WHISPER_COMBAT_END_WIPE_AT 		= "%s зазнав поразки від %s на %s"
DBM_CORE_WHISPER_COMBAT_END_WIPE_STATS_AT	= "%s зазнав поразки від %s на %s. Загальна кількість вайпів у них - %d."
--Scenarios (no percents. words like "fighting" or "wipe" changed to better fit scenarios)
DBM_CORE_AUTO_RESPOND_WHISPER_SCENARIO 		= "%s зараз зайнятий у %s (%d/%d людей живі)"
DBM_CORE_WHISPER_SCENARIO_END_KILL 			= "%s завершив %s!"
DBM_CORE_WHISPER_SCENARIO_END_KILL_STATS 	= "%s завершив %s! Загальна кількість перемог у них - %d."
DBM_CORE_WHISPER_SCENARIO_END_WIPE 			= "%s не завершив %s"
DBM_CORE_WHISPER_SCENARIO_END_WIPE_STATS 	= "%s не завершив %s. Загальна кількість незавершених у них - %d."

DBM_CORE_VERSIONCHECK_HEADER 		= "Boss Masters - Версії"
DBM_CORE_VERSIONCHECK_ENTRY 		= "%s: %s (%s)"
DBM_CORE_VERSIONCHECK_ENTRY_TWO 	= "%s: %s (%s) & %s (%s)"
DBM_CORE_VERSIONCHECK_ENTRY_NO_DBM 	= "%s: Boss Master не встановлено."
DBM_CORE_VERSIONCHECK_FOOTER 		= "Знайдено %d |4гравець:гравця:гравців; з DBM і %d |4гравець:гравця:гравців; з Bigwigs."
DBM_CORE_VERSIONCHECK_OUTDATED 		= "Наступні %d гравець(и) мають застарілу версію: %s."
DBM_CORE_YOUR_VERSION_OUTDATED 		= "УВАГА! Ваша версія DBM застаріла! Будь ласка, відвідайте " .. DBM_CORE_UPDATEREMINDER_URL .. " для оновлення на останню версію (rus and eng)."
DBM_CORE_VOICE_PACK_OUTDATED 		= "У вашому голосовому пакеті DBM відсутні звуки, підтримувані цією версією DBM. Фільтр звуків спец-попереджень було вимкнено. Будь ласка, скачайте оновлену версію голосового пакета або зв'яжіться з автором для оновлення, яке містить відсутні звукові файли."
DBM_CORE_VOICE_MISSING 				= "Обраний вами голосовий пакет DBM не знайдено. Ваш вибір було скинуто на 'None'. Якщо це помилка, переконайтеся, що ваш голосовий пакет правильно встановлений і ввімкнений у модифікаціях."
DBM_CORE_VOICE_DISABLED 			= "У вас встановлений принаймні один голосовий пакет DBM, але жоден з них не ввімкнений. Якщо ви збираєтеся використовувати голосовий пакет, переконайтеся, що він обраний у 'Звукові сповіщення', інакше видаліть невикористані голосові пакети, щоб приховати це повідомлення."
DBM_CORE_VOICE_COUNT_MISSING 		= "Голос зворотного відліку %d налаштований на голосовий пакет, який не може бути знайдений. Він має бути скинутий до налаштувань за замовчуванням."
DBM_BIG_WIGS 						= "BigWigs"

DBM_CORE_UPDATEREMINDER_HEADER 			= "Ваша версія Dungeon Boss Master застаріла.\n Версія %s (r%d) доступна для завантаження тут: " .. DBM_CORE_UPDATEREMINDER_URL .. "."
DBM_CORE_UPDATEREMINDER_HEADER_ALPHA 	= "Ваша альфа версія Dungeon Boss Master застаріла.\n Ви принаймні %d тестових версій позаду. Користувачам DBM рекомендується використовувати останню альфа або останню стабільну версію. Застарілі альфи можуть призвести до поганої або неповної функціональності."
DBM_CORE_UPDATEREMINDER_FOOTER 			= "Натисніть " .. (IsMacClient() and "Cmd-C" or "Ctrl-C")  ..  ", щоб скопіювати посилання завантаження в буфер обміну."
DBM_CORE_UPDATEREMINDER_FOOTER_GENERIC 	= "Натисніть " .. (IsMacClient() and "Cmd-C" or "Ctrl-C")  ..  ", щоб скопіювати посилання в буфер обміну."
DBM_CORE_UPDATEREMINDER_DISABLE 		= "ПОПЕРЕДЖЕННЯ: У зв'язку з тим, що Ваш Dungeon Boss Master сильно застарів (%d ревізій), його було відключено до оновлення. Це зроблено для того, щоб старий і несумісний код не викликав поганий ігровий досвід для Вас та інших членів рейду."
DBM_CORE_UPDATEREMINDER_DISABLE2 		= "ПОПЕРЕДЖЕННЯ: У зв'язку з тим, що хтось із рейду використовує палену версію аддону - ваша вважається застарілою і повинна бути відключена назовсім. Але не турбуйтеся, тому що ця версія є роботою гравця Aleksart163 - аддон і далі продовжить роботу, але все одно рекомендується відвідати " .. DBM_CORE_UPDATEREMINDER_URL .. " для оновлення."
DBM_CORE_UPDATEREMINDER_HOTFIX 			= "Ваша версія DBM матиме некоректні таймери або попередження під час цього енкаунтера. Це виправлено в новій версії (або альфа-версії, якщо нова версія не доступна)."
DBM_CORE_UPDATEREMINDER_HOTFIX_ALPHA	= DBM_CORE_UPDATEREMINDER_HOTFIX--TEMP, FIX ME!
DBM_CORE_UPDATEREMINDER_MAJORPATCH 		= "ПОПЕРЕДЖЕННЯ: Через те, що ваш Dungeon Boss Master застарів, його відключили до оновлення, тому що це великий ігровий патч. Це необхідно для того, щоб старий і несумісний код не призводив до погіршення ігрового досвіду для вас і членів вашого рейду. Переконайтеся що ви завантажили нову версію з " .. DBM_CORE_UPDATEREMINDER_URL .. " як тільки вона стане доступною."
DBM_CORE_UPDATEREMINDER_TESTVERSION 	= "ПОПЕРЕДЖЕННЯ: Ви використовуєте версію Dungeon Boss Master, не призначену для використання з цією версією гри. Будь ласка, переконайтеся, що ви завантажили відповідну версію для вашого ігрового клієнта з сайту " .. DBM_CORE_UPDATEREMINDER_URL .. "."
DBM_CORE_VEM 							= "ПОПЕРЕДЖЕННЯ: Ви використовуєте Dungeon Boss Master і Voice Encounter Mods одночасно. DBM не було завантажено, тому що ці два аддони не можуть працювати разом."
DBM_CORE_3RDPROFILES 					= "ПОПЕРЕДЖЕННЯ: DBM-Profiles не сумісний з цією версією DBM. Він повинен бути видалений перш ніж DBM зможе продовжити, щоб уникнути конфліктів."
DBM_CORE_DPMCORE 						= "ПОПЕРЕДЖЕННЯ: Deadly PvP mods не сумісні з цією версією DBM. Щоб продовжити, видаліть їх, щоб уникнути конфліктів."
DBM_CORE_UPDATE_REQUIRES_RELAUNCH 		= "ПОПЕРЕДЖЕННЯ: Це оновлення DBM не працюватиме коректно, якщо ви не перезапустите ігровий клієнт. Це оновлення містить нові файли або зміни в .toc файлі, які не можуть бути завантажені через ReloadUI. Ви можете зіткнутися зі зламаною функціональністю або помилками якщо продовжите без перезапуску клієнта."
DBM_CORE_OUT_OF_DATE_NAG 				= "Ваша версія Dungeon Boss Master застаріла і Ви вибрали опцію ігнорувати спливаюче повідомлення. Рекомендується оновитися, щоб не було відсутніх важливих попереджень або таймерів, або крику від Вас, на який розраховує решта рейду."

DBM_CORE_MOVABLE_BAR				= "Перетягніть!"

DBM_PIZZA_SYNC_INFO					= "|Hplayer:%1$s|h[%1$s]|h транслює DBM Timer: '%2$s'\n|HDBM:cancel:%2$s:nil|h|cff3588ff[Скасувати цей DBM Timer]|r|h |HDBM:ignore:%2$s:%1$s|h|cff3588ff[Ігнорувати DBM Timer від %1$s]|r|h"
DBM_PIZZA_CONFIRM_IGNORE 			= "Ігнорувати DBM таймери від %s на час поточного сеансу?"
DBM_PIZZA_ERROR_USAGE				= "Использование: /dbm [broadcast] timer <time> <text>. <time> должно быть больше 1."

DBM_CORE_MINIMAP_TOOLTIP_HEADER		= "Dungeon Boss Master"
DBM_CORE_MINIMAP_TOOLTIP_FOOTER		= "Shift+клацання або клацніть правою кнопкою миші, щоб перемістити\nAlt+shift+клацання для вільного перетягування"

DBM_CORE_RANGECHECK_HEADER 			= "Перевірка дистанції (%d м)"
DBM_CORE_RANGECHECK_SETRANGE 		= "Налаштування дистанції"
DBM_CORE_RANGECHECK_SETTHRESHOLD 	= "Налаштування порога гравців"
DBM_CORE_RANGECHECK_SOUNDS 			= "Звуковий сигнал"
DBM_CORE_RANGECHECK_SOUND_OPTION_1 	= "Один з гравців підійшов до вас занадто близько"
DBM_CORE_RANGECHECK_SOUND_OPTION_2 	= "Декілька людей перебувають біля вас"
DBM_CORE_RANGECHECK_SOUND_0 		= "Без звуку"
DBM_CORE_RANGECHECK_SOUND_1 		= "За замовчуванням"
DBM_CORE_RANGECHECK_SOUND_2 		= "Дратівливий звуковий сигнал"
DBM_CORE_RANGECHECK_SETRANGE_TO 	= "%d м"
DBM_CORE_RANGECHECK_OPTION_FRAMES 	= "Фрейми"
DBM_CORE_RANGECHECK_OPTION_RADAR 	= "Показувати радар"
DBM_CORE_RANGECHECK_OPTION_TEXT 	= "Показувати текстовий фрейм"
DBM_CORE_RANGECHECK_OPTION_BOTH 	= "Показувати обидва фрейми"
DBM_CORE_RANGERADAR_HEADER 			= "Радар (%d ярдів)"
DBM_CORE_RANGERADAR_IN_RANGE_TEXT	= "%d гравців у радіусі"
DBM_CORE_RANGERADAR_IN_RANGE_TEXTONE = "%s (%0.1fм)"

DBM_CORE_INFOFRAME_SHOW_SELF 		= "Завжди показувати вашу енергію"
DBM_CORE_INFOFRAME_SETLINES 		= "Встановіть максимальну кількість рядків"
DBM_CORE_INFOFRAME_LINESDEFAULT 	= "Встановлено модом"
DBM_CORE_INFOFRAME_LINES_TO 		= "%d рядків"
DBM_CORE_INFOFRAME_POWER 			= "Потужність"
DBM_CORE_INFOFRAME_MAIN 			= "Основна:"
DBM_CORE_INFOFRAME_ALT 				= "Альтер.:"

DBM_LFG_INVITE 						= "Запрошення в підземелля"
DBM_PHASE 							= "%d-й етап"


DBM_CORE_SLASHCMD_HELP				= {
	"Доступні слеш команди:",
	"-----------------",
	"/dbm unlock: Відображає переміщуваний індикатор таймера (псевдонім: move).",
	"/range <число> or /distance <число>: Показати вікно перевірки дистанції. /rrange або /rdistance для зворотних кольорів.",
	"/hudar <число>: Перевірка дистанції, що використовує HUD.",
	"/dbm timer: Запускає користувацький відлік часу, для доп. інформації введіть '/dbm timer'.",
	"/dbm arrow: Показує стрілку DBM, для дод. інформації введіть '/dbm arrow help'.",
	"/dbm hud: Показує DBM HUD, для дод. інформації введіть '/dbm hud'.",
	"/dbm help2: Показує команди керування рейдом"
}
DBM_CORE_SLASHCMD_HELP2				= {
	"Доступні слеш команди:",
	"-----------------",
	"/dbm pull <сек>: Транслює відлік часу до атаки всім членам рейду (потрібні права лідера або помічника).",
	"/dbm break <хв>: Транслює відлік часу відпочинку всім членам рейду (потрібні права лідера або помічника).", "/dbm break <хв>: Транслює відлік часу відпочинку всім членам рейду (потрібні права лідера або помічника).",
	"/dbm version: Виконує перевірку використовуваної рейдом версії (псевдонім: ver).",
	"/dbm version2: Виконує перевірку використовуваної рейдом версії та надсилає повідомлення пошепки членам рейду із застарілою версією (псевдонім: ver2).",
	"/dbm lockout: Отримати список поточних збережень підземель у членів рейду (псевдоніми: lockouts, ids) (потрібні права лідера або помічника).",
	"/dbm lag: Виконує перевірку затримки у всього рейду.",
	"/dbm durability: Виконує перевірку міцності речей усього рейду."
}
DBM_CORE_TIMER_USAGE	= {
	"Команди таймерів DBM:",
	"-----------------",
	"/dbm timer <сек> <текст>: Запускає таймер із зазначеним текстом.",
	"/dbm ctimer <сек> <текст>: Запускає таймер із текстом зворотного відліку.",
	"/dbm ltimer <сек> <текст>: Запускає таймер, який автоматично повторюється до скасування.",
	"/dbm cltimer <сек> <текст>: Запускає таймер із текстом зворотного відліку, який автоматично повторюється до скасування.",
	"Додайте 'broadcast' перед типом таймера, щоб поділитися ним із рейдом (потрібні права лідера або помічника).",
	"/dbm timer endloop: Зупиняє будь-який повторюваний ltimer або cltimer.", "/dbm timer endloop: Зупиняє будь-який повторюваний ltimer або cltimer."
}

DBM_ERROR_NO_PERMISSION				= "У вас недостатньо прав для виконання цієї операції."

--Common Locals
DBM_NEXT 							= "Слід. %s"
DBM_COOLDOWN 						= "Відновлення %s"
DBM_CORE_UNKNOWN 					= "невідомо"
DBM_CORE_LEFT 						= "Ліворуч"
DBM_CORE_RIGHT 						= "Направо"
DBM_CORE_BACK 						= "Назад"
DBM_CORE_SIDE 						= "Сторона"
DBM_CORE_TOP 						= "Верх"
DBM_CORE_BOTTOM 					= "Низ"
DBM_CORE_MIDDLE 					= "Центр"
DBM_CORE_FRONT 						= "Вперед"
DBM_CORE_EAST 						= "Схід"
DBM_CORE_WEST 						= "Захід"
DBM_CORE_NORTH 						= "Північ"
DBM_CORE_SOUTH 						= "Південь"
DBM_CORE_INTERMISSION 				= "Перехідна фаза"
DBM_CORE_ORB 						= "Сфера"
DBM_CHEST 							= "скриня"
DBM_NO_DEBUFF 						= "Немає %s"
DBM_ALLY 							= "Союзник"
DBM_ADD 							= "Cміття"--A fight Add as in "boss spawned extra adds"
DBM_ADDS 							= "Cміття"
DBM_CORE_ROOM_EDGE 					= "краю кімнати"
DBM_CORE_FAR_AWAY 					= "Вдалині"
DBM_CORE_BREAK_LOS 					= "Перерва LOS"
DBM_CORE_SAFE 						= "Безпека"
DBM_CORE_SHIELD 					= "Щит"
DBM_CORE_SPHERE 					= "Сферу"
DBM_CORE_TOTHEBOSS 					= "Босу"
DBM_INCOMING 						= "%s прибувають"
--DBM_SUMMON1 						= " отримав суммон від "
--DBM_SUMMON2 						= "прийняв суммон"
--Common Locals end

DBM_CORE_BREAK_USAGE 				= "Перерва не може бути довшою за 60 хвилин. Переконайтеся що ви вводите час у хвилинах, а не секундах."
DBM_CORE_BREAK_START 				= "Перерва починається -- у вас є %s! (відправив %s)"
DBM_CORE_BREAK_MIN 					= "Перерва закінчується через %s хв.!"
DBM_CORE_BREAK_SEC 					= "Перерва закінчується через %s сек.!"
DBM_CORE_TIMER_BREAK 				= "Перерва!"
DBM_CORE_ANNOUNCE_BREAK_OVER 		= "Перерва закінчилася"

DBM_CORE_TIMER_PULL 				= "Атака"
DBM_CORE_ANNOUNCE_PULL 				= "Атака через %d сек. (відправив %s)"
DBM_CORE_ANNOUNCE_PULL_NOW 			= "Атака!"
DBM_CORE_ANNOUNCE_PULL_TARGET 		= "Атакуємо %s через %d сек. (відправив %s)"
DBM_CORE_ANNOUNCE_PULL_NOW_TARGET 	= "Атакуємо %s!"
DBM_CORE_GEAR_WARNING 				= "Увага: Перевірка екіпіровки. Рівень вдягнутих предметів на %d нижчий за максимальний"
DBM_CORE_GEAR_WARNING_WEAPON 		= "Увага: Перевірте, чи одягнена у вас коректна зброя."
DBM_CORE_GEAR_FISHING_POLE 			= "Вудка"

DBM_CORE_ACHIEVEMENT_TIMER_SPEED_KILL = "Досягнення"

-- Auto-generated Warning Localizations
DBM_CORE_AUTO_ANNOUNCE_TEXTS.you 			= "%s на тобі"
DBM_CORE_AUTO_ANNOUNCE_TEXTS.target 		= "%s на |3-5(>%%%s<)"
DBM_CORE_AUTO_ANNOUNCE_TEXTS.targetsource 	= ">%%s< застосовує %s"
DBM_CORE_AUTO_ANNOUNCE_TEXTS.targetsource2 	= ">%%s< застосовує %s на >%%s<"
DBM_CORE_AUTO_ANNOUNCE_TEXTS.targetsourcecount = ">%%s< застосовує %s (%%s)"
DBM_CORE_AUTO_ANNOUNCE_TEXTS.targetcount 	= "%s (%%s) на |3-5(>%%s<)"
DBM_CORE_AUTO_ANNOUNCE_TEXTS.spell 			= "%s"
DBM_CORE_AUTO_ANNOUNCE_TEXTS.ends 			= "%s закінчується"
DBM_CORE_AUTO_ANNOUNCE_TEXTS.endtarget 		= "%s закінчується на >%%s<"
DBM_CORE_AUTO_ANNOUNCE_TEXTS.fades 			= "%s спадає"
DBM_CORE_AUTO_ANNOUNCE_TEXTS.adds 			= "Залишилося %s: %%d"
DBM_CORE_AUTO_ANNOUNCE_TEXTS.cast 			= "Застосування %s: %.1f сек"
DBM_CORE_AUTO_ANNOUNCE_TEXTS.soon 			= "Скоро %s"
DBM_CORE_AUTO_ANNOUNCE_TEXTS.prewarn 		= "%s через %s"
DBM_CORE_AUTO_ANNOUNCE_TEXTS.stage 			= "Фаза %s"
DBM_CORE_AUTO_ANNOUNCE_TEXTS.prestage 		= "Скоро фаза %s"
DBM_CORE_AUTO_ANNOUNCE_TEXTS.count 			= "%s (%%s)"
DBM_CORE_AUTO_ANNOUNCE_TEXTS.stack 			= "%s на |3-5(>%%%s<) (%%d)"

local prewarnOption 						= "Попереджати заздалегідь про $spell:%s"
DBM_CORE_AUTO_ANNOUNCE_OPTIONS.you 			= "Оголошувати коли $spell:%s на тобі"
DBM_CORE_AUTO_ANNOUNCE_OPTIONS.target 		= "Оголошувати цілі заклинання $spell:%s"
DBM_CORE_AUTO_ANNOUNCE_OPTIONS.targetsource = "Оголошувати джерело використання заклинання $spell:%s"
DBM_CORE_AUTO_ANNOUNCE_OPTIONS.targetsource2 = "Оголошувати (з метою) джерело використання заклинання $spell:%s"
DBM_CORE_AUTO_ANNOUNCE_OPTIONS.targetsourcecount = "Оголошувати (з лічильником) джерело використання заклинання $spell:%s"
DBM_CORE_AUTO_ANNOUNCE_OPTIONS.targetcount 	= "Оголошувати цілі заклинання $spell:%s (з лічильником)"
DBM_CORE_AUTO_ANNOUNCE_OPTIONS.spell 		= "Попередження для $spell:%s"
DBM_CORE_AUTO_ANNOUNCE_OPTIONS.ends 		= "Попереджати про закінчення $spell:%s"
DBM_CORE_AUTO_ANNOUNCE_OPTIONS.endtarget	= "Попереджати про закінчення $spell:%s (ціль)"
DBM_CORE_AUTO_ANNOUNCE_OPTIONS.fades 		= "Попереджати про спадання $spell:%s"
DBM_CORE_AUTO_ANNOUNCE_OPTIONS.adds 		= "Оголошувати скільки залишилося $spell:%s"
DBM_CORE_AUTO_ANNOUNCE_OPTIONS.cast 		= "Попереджати про застосування заклинання $spell:%s"
DBM_CORE_AUTO_ANNOUNCE_OPTIONS.soon 		= prewarnOption
DBM_CORE_AUTO_ANNOUNCE_OPTIONS.prewarn 		= prewarnOption
DBM_CORE_AUTO_ANNOUNCE_OPTIONS.stage 		= "Оголошувати фазу %s"
DBM_CORE_AUTO_ANNOUNCE_OPTIONS.stagechange 	= "Оголошувати зміни фаз"
DBM_CORE_AUTO_ANNOUNCE_OPTIONS.prestage 	= "Попереджати заздалегідь про фазу %s"
DBM_CORE_AUTO_ANNOUNCE_OPTIONS.count 		= "Попередження для $spell:%s (з лічильником)"
DBM_CORE_AUTO_ANNOUNCE_OPTIONS.stack 		= "Оголошувати кількість стаків $spell:%s"

DBM_CORE_AUTO_SPEC_WARN_TEXTS.spell 			= "%s!"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.ends 				= "%s закінчується"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.ready 			= "%s готово"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.fades 			= "%s спадає"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.youfades 			= "%s спадає з тебе"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.soon 				= "Скоро %s"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.soonparaxiscount 	= "Скоро %s - %%s група"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.soonlookaway 		= "Скоро %s - відвернися"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.prewarn 			= "%s через %s"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.dispel 			= "%s на |3-5(>%%%s<) - розсійся"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.interrupt 		= "%s - перерви каст!"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.interrupt2 		= "%s - перерви каст контролем!"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.interruptcount 	= "%s - перерви каст! (%%d)"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.interruptcount2 	= "%s! (%%s) - перерви каст"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.you 				= "%s на вас"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.youdispel 		= "%s на вас - розсіяти"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.youcount 			= "%s (%%s) на вас!"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.youpos 			= "%s (%%s) на вас"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.soak 				= "%s! - повторно вирізати"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.soakcount 		= "%s (%%s) - надрізати"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.soakpos 			= "%s (Позиція перегляду: %%s)"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.target 			= "%s до >%%s<"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.targethelp 		= "%s на >%%s< - допомога"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.targetdodge 		= "%s на >%%s< - уникати"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.targetsoak 		= "%s на >%%s< - вирізати"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.targetrun 		= "%s на >%%s< - виконати"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.targetint 		= "%s на >%%s< - перервати приведення!"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.targetcount 		= "%s (%%s) на >%%s< "
DBM_CORE_AUTO_SPEC_WARN_TEXTS.youdefensive 		= "%s на вас! - захистити"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.defensive 		= "%s! - захистити"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.defensivecount 	= "%s! (%%s) - захистити"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.taunt 			= "%s on >%%s< - taunt"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.youclose 			= "%s на >%%s< - розділити з ним шкоду"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.close 			= "%s на |3-5(>%%s<) біля вас"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.closeemoveaway 	= "%s на >%%s< - тікайте"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.move 				= "%s - втекти"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.youmove 			= "%s під вами - тікайте"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.dontmove 			= "%s! - не рухатися"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.youdontmove 		= "%s під вами! - не рухатися"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.dontstand 		= "%s! - не стій на місці"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.youdontstand 		= "%s на тобі! - не стій на місці"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.dodge 			= "%s - уникати"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.dodgecount 		= "%s (%%s) - уникати"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.dodgeloc 			= "%s - ухилення %%s"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.youmoveaway 		= "%s на тобі! - відбіжи від інших"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.moveaway 			= "%s - відбіжи від інших"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.moveboss 			= "%s - біжи до боса"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.moveto 			= "%s - біжи до >%%s<"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.youmovetopos 		= "%s (%%s) на тобі! - біжи до мітки"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.youshare 			= "%s на тобі! - розділи шкоду з іншими"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.share 			= "%s! - розділи шкоду"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.sharecount 		= "%s! (%%s) - розділи урон"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.jump 				= "%s - підстрибни"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.run 				= "%s - тікай"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.yourun 			= "%s на тобі! - тікай"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.running 			= "%s! - збіжіться разом"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.yourunning 		= "%s на тобі! - збіжіться разом"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.runningcount 		= "%s! (%%s) - збіжіться разом"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.cast 				= "%s - перерви свій каст!"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.lookaway 			= "%s! - відвернися"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.youlookaway2 		= "%s на тобі! - відвернися від інших"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.youlook 			= "%s на тобі! - дивись на >%%s<"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.youfind 			= "%s на тобі! - поверни свою душу"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.reflect 			= "%s на |3-5(>%%%s<) - припини атаку"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.count 			= "%s! (%%s)"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.stack 			= "На тобі %%d стаків %s"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.switch 			= "%s - перемкнися"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.switch2 			= "%s - перемкнися на >%%s<"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.switchcount 		= "%s - перемкнися (%%s)"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.gtfo 				= "%%s під тобою - відійди"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.Adds 				= "Прибуття трешу - перемкнися"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.Addscustom 		= "Прибуття трешу - %%s"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.icepud 			= "%s! - біжи в калюжу льоду"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.moredamage 		= "%s - більше шкоди"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.youmoredamage 	= "%s на тобі! - дай більше шкоди"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.paraxiscount 		= "%s - черга %%s групи"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.standsand 		= "%s - встань на пісок"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.useitem 			= "%s - використовуй >%%s<"
DBM_CORE_AUTO_SPEC_WARN_TEXTS.keepdist 			= "%s - тримай дистанцію (%%s)м"

-- Auto-generated Special Warning Localizations
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.spell 			= "Спец-попередження для $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.ends 			= "Спец-попередження про закінчення $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.ready 			= "Спец-попередження про готовність $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.fades 			= "Спец-попередження про спадання $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.youfades 		= "Спец-попередження коли з вас спадає $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.soon 			= "Спец-попередження що скоро $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.soonparaxiscount = "Спец-попередження (з лічильником групи) що скоро $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.soonlookaway 	= "Спец-попередження \"відверніться\", коли скоро $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.prewarn 		= "Спец-попередження за %s сек. до $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.dispel 			= "Спец-попередження для розсіювання/викрадення заклинання $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.interrupt 		= "Спец-попередження \"перервіть каст\" для заклинання $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.interrupt2 		= "Спец-попередження \"перервіть каст своїм контролем\" для заклинання $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.interruptcount 	= "Спец-попередження (з лічильником) \"перервіть каст\" для заклинання $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.interruptcount2 = "Спец-попередження (з лічильником) \"перервіть каст\" для заклинання $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.you 			= "Спец-попередження коли на вас $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.youdispel 		= "Спец-попередження для розсіювання заклинання коли на вас $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.youcount 		= "Спец-попередження (з лічильником), коли на вас $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.youpos 			= "Спец-попередження (з позицією) коли на вас $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.soak 			= "Спец-попередження \"перекрийте\" для $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.soakcount 		= "Спец-попередження (з лічильником) \"перекрийте\" для $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.soakpos 		= "Спец-попередження (з позицією) для допомоги з поглинанням $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.target 			= "Спец-попередження коли на комусь $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.targethelp 		= "Спец-попередження (з іменем) \"допоможіть\", коли на комусь $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.targetdodge 	= "Спец-попередження (з іменем) \"уникайте\", коли на комусь $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.targetsoak 		= "Спец-попередження (з іменем) \"перекрийте\", коли на комусь $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.targetrun 		= "Спец-попередження (з іменем) \"біжіть\", коли на комусь $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.targetint 		= "Спец-попередження (з ім'ям) \"перервіть каст\", коли на комусь $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.targetcount 	= "Спец-попередження (з лічильником), коли на комусь $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.youdefensive 	= "Спец-попередження для використання захисних здібностей, коли на вас $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.defensive 		= "Спец-попередження для використання захисних здібностей від $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.defensivecount 	= "Спец-попередження (з лічильником) для використання захисних здібностей від $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.taunt 			= "Спец-попередження \"затаунті\", коли на іншому танку $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.youclose 		= "Спец-попередження \"поділіть шкоду між собою\", коли на комусь поруч із вами $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.close 			= "Спец-попередження коли на комусь поруч із вами $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.closemoveaway 	= "Спец-попередження \"відбіжіть від союзника\", коли на комусь поруч із вами $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.move 			= "Спец-попередження \"відбіжіть\" для $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.youmove 		= "Спец-попередження \"відбіжіть\" коли під вами $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.dontmove 		= "Спец-попередження \"не рухайтеся\" для $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.youdontmove 	= "Спец-попередження \"не рухайтеся\" коли під вами $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.dontstand 		= "Спец-попередження \"не стійте на місці\" для $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.youdontstand 	= "Спец-попередження \"не стійте на місці\" коли ви ціль $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.dodge 			= "Спец-попередження \"уникайте\" для $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.dodgecount 		= "Спец-попередження (з лічильником) \"уникайте\" для $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.dodgeloc 		= "Спец-попередження (з місцем розташування) \"уникайте\" для ухилення від $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.youmoveaway 	= "Спец-попередження \"відбіжіть від інших\", коли на вас $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.moveaway 		= "Спец-попередження \"відбіжіть від інших\" для $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.moveboss 		= "Спец-попередження \"біжіть до боса\" для $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.moveto 			= "Спец-попередження \"біжіть до когось\", на кому $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.youmovetopos 	= "Спец-попередження \"біжіть до своєї мітки\" (з позицією), коли на вас $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.youshare 		= "Спец-попередження \"поділіть шкоду з іншими\", коли на вас $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.share 			= "Спец-попередження \"поділіть шкоду з іншими\" для $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.sharecount 		= "Спец-попередження (з лічильником) \"поділіть шкоду з іншими\" для $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.jump 			= "Спец-попередження \"підстрибніть\" для $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.run 			= "Спец-попередження \"тікайте\" для $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.yourun 			= "Спец-попередження \"тікайте\" коли ви ціль $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.running 		= "Спец-попередження \"збіжіться разом\" для $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.yourunning 		= "Спец-попередження \"збіжіться разом\" коли ви ціль $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.runningcount 	= "Спец-попередження (з лічильником) \"збіжіться разом\" для $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.cast 			= "Спец-попередження \"перервіть свій каст\" для $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.lookaway 		= "Спец-попередження \"відверніться\" для $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.youlookaway2 	= "Спец-попередження \"відверніться від інших\" коли на вас $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.youlook 		= "Спец-попередження \"дивіться на ...\" коли ви ціль $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.youfind 		= "Спец-попередження \"поверніть свою духовну енергію\" коли ви ціль $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.reflect 		= "Спец-попередження \"припиніть атаку\" для $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.count 			= "Спец-попередження (з лічильником) для $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.stack 			= "Спец-попередження коли на вас >=%d стаків $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.switch 			= "Спец-попередження про зміну цілі для $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.switch2 		= "Спец-попередження про зміну цілі, коли на комусь $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.switchcount 	= "Спец-попередження (з лічильником) про зміну цілі для $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.gtfo 			= "Спец-попередження, коли під вами всякі неприємні калюжі"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.Adds 			= "Спец-попередження про зміну цілі під час прибуття трешу"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.Addscustom 		= "Спец-попередження під час прибуття трешу"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.icepud 			= "Спец-попередження \"біжи в калюжу льоду\" під час дії $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.moredamage 		= "Спец-попередження \"більше шкоди\" коли на комусь $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.youmoredamage 	= "Спец-попередження \"дайте більше шкоди\" коли на вас $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.paraxiscount 	= "Спец-попередження (з лічильником) \"черга ... групи\" для $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.standsand 		= "Спец-попередження \"встаньте на пісок\" для $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.useitem 		= "Спец-попередження \"використовуйте\" на ком $spell:%s"
DBM_CORE_AUTO_SPEC_WARN_OPTIONS.keepdist 		= "Спец-попередження \"тримайте дистанцію N метрів\" для $spell:%s"

-- Auto-generated Timer Localizations
DBM_CORE_AUTO_TIMER_TEXTS.target 		= "%s: >%%s<"
DBM_CORE_AUTO_TIMER_TEXTS.cast 			= "%s"
DBM_CORE_AUTO_TIMER_TEXTS.castsource 	= "%s: %%s"
DBM_CORE_AUTO_TIMER_TEXTS.active 		= "%s закінчується" --Buff/Debuff/event on boss
DBM_CORE_AUTO_TIMER_TEXTS.fades 		= "%s спадає" --Buff/Debuff on players
DBM_CORE_AUTO_TIMER_TEXTS.ai 			= "%s IІ"
DBM_CORE_AUTO_TIMER_TEXTS.cd 			= "~ %s"
DBM_CORE_AUTO_TIMER_TEXTS.cdcount		= "~ %s (%%s)"
DBM_CORE_AUTO_TIMER_TEXTS.cdsource 		= "~ %s: >%%s<"
DBM_CORE_AUTO_TIMER_TEXTS.cdspecial 	= "~ спец-здатність"
DBM_CORE_AUTO_TIMER_TEXTS.next 			= "~ %s"
DBM_CORE_AUTO_TIMER_TEXTS.nextcount 	= "~ %s (%%s)"
DBM_CORE_AUTO_TIMER_TEXTS.nextsource 	= "~ %s: >%%s<"
DBM_CORE_AUTO_TIMER_TEXTS.nextspecial 	= "~ спец-здатність"
DBM_CORE_AUTO_TIMER_TEXTS.achievement 	= "%s"
DBM_CORE_AUTO_TIMER_TEXTS.stage 		= "Наслід. фаза"
DBM_CORE_AUTO_TIMER_TEXTS.adds 			= "Прибуття аддів"
DBM_CORE_AUTO_TIMER_TEXTS.addscustom 	= "Прибуття аддів (%%s)"
DBM_CORE_AUTO_TIMER_TEXTS.roleplay		= GUILD_INTEREST_RP

DBM_CORE_AUTO_TIMER_OPTIONS.target 		= "Відлік часу дії дебаффа $spell:%s"
DBM_CORE_AUTO_TIMER_OPTIONS.cast 		= "Відлік часу застосування заклинання $spell:%s"
DBM_CORE_AUTO_TIMER_OPTIONS.castsource 	= "Відлік часу застосування заклинання (з джерелом) для $spell:%s"
DBM_CORE_AUTO_TIMER_OPTIONS.active 		= "Відлік часу дії $spell:%s"
DBM_CORE_AUTO_TIMER_OPTIONS.fades 		= "Відлік часу до спадання $spell:%s з цілі"
DBM_CORE_AUTO_TIMER_OPTIONS.ai 			= "Відлік часу до відновлення $spell:%s (ШІ)"
DBM_CORE_AUTO_TIMER_OPTIONS.cd 			= "Відлік часу до відновлення $spell:%s"
DBM_CORE_AUTO_TIMER_OPTIONS.cdcount 	= "Відлік часу до відновлення (з лічильником) $spell:%s"
DBM_CORE_AUTO_TIMER_OPTIONS.cdsource 	= "Відлік часу до відновлення $spell:%s (із джерелом)"
DBM_CORE_AUTO_TIMER_OPTIONS.cdspecial 	= "Відлік часу до відновлення спец-здатності"
DBM_CORE_AUTO_TIMER_OPTIONS.next 		= "Відлік часу до наступного $spell:%s"
DBM_CORE_AUTO_TIMER_OPTIONS.nextcount 	= "Відлік часу до наступного (з лічильником) $spell:%s"
DBM_CORE_AUTO_TIMER_OPTIONS.nextsource 	= "Відлік часу до наступного $spell:%s (із джерелом)"
DBM_CORE_AUTO_TIMER_OPTIONS.nextspecial = "Відлік часу до наступної спец-здатності"
DBM_CORE_AUTO_TIMER_OPTIONS.achievement = "Відлік часу для %s"
DBM_CORE_AUTO_TIMER_OPTIONS.stage 		= "Відлік часу до наступної фази"
DBM_CORE_AUTO_TIMER_OPTIONS.adds 		= "Відлік часу до прибуття аддів"
DBM_CORE_AUTO_TIMER_OPTIONS.addscustom 	= "Відлік часу до прибуття аддів"
DBM_CORE_AUTO_TIMER_OPTIONS.roleplay 	= "Відлік часу для рольової гри"

DBM_CORE_AUTO_ICONS_OPTION_TEXT 		= "Встановлювати мітки на цілі заклинання $spell:%s"
DBM_CORE_AUTO_ICONS_OPTION_TEXT2 		= "Встановлювати мітки на $spell:%s"
DBM_CORE_AUTO_ARROW_OPTION_TEXT 		= "Показувати стрілку DBM до цілі, на якій $spell:%s"
DBM_CORE_AUTO_ARROW_OPTION_TEXT2 		= "Показувати стрілку DBM від цілі, на якій $spell:%s"
DBM_CORE_AUTO_ARROW_OPTION_TEXT3 		= "Показувати стрілку DBM до певного місця для $spell:%s"
DBM_CORE_AUTO_VOICE_OPTION_TEXT 		= "Звукове сповіщення для $spell:%s"
DBM_CORE_AUTO_VOICE2_OPTION_TEXT 		= "Звукове сповіщення про зміни фаз"
DBM_CORE_AUTO_VOICE3_OPTION_TEXT 		= "Звукове сповіщення для прибуваючих аддів"
DBM_CORE_AUTO_VOICE4_OPTION_TEXT 		= "Звукове сповіщення коли під вами всякі калюжі"
DBM_CORE_AUTO_COUNTDOWN_OPTION_TEXT 	= "Звуковий відлік до відновлення $spell:%s"
DBM_CORE_AUTO_COUNTDOWN_OPTION_TEXT2 	= "Звуковий відлік до спадання $spell:%s"
DBM_CORE_AUTO_COUNTOUT_OPTION_TEXT		= "Звуковий відлік під час дії $spell:%s"

DBM_CORE_AUTO_YELL_OPTION_TEXT.shortyell 	= "Кричати, коли на вас $spell:%s"
DBM_CORE_AUTO_YELL_OPTION_TEXT.yell 		= "Кричати (з ім'ям гравця), коли на вас $spell:%s"
DBM_CORE_AUTO_YELL_OPTION_TEXT.yellhelp 	= "Кричати (з проханням про допомогу), коли на вас $spell:%s"
DBM_CORE_AUTO_YELL_OPTION_TEXT.yelldispel 	= "Кричати (з проханням допомоги розсіювання), коли на вас $spell:%s"
DBM_CORE_AUTO_YELL_OPTION_TEXT.yellmoveaway = "Кричати (з попередженням \"відбіжіть\"), коли на вас $spell:%s"
DBM_CORE_AUTO_YELL_OPTION_TEXT.count 		= "Кричати (з лічильником), коли на вас $spell:%s"
DBM_CORE_AUTO_YELL_OPTION_TEXT.fade 		= "Кричати (зі зворотним відліком і назвою дебаффа), коли $spell:%s з вас спадає"
DBM_CORE_AUTO_YELL_OPTION_TEXT.fademoveaway = "Кричати (зі зворотним відліком, назвою дебаффа і з попередженням \"відбіжіть\"), коли $spell:%s з вас спадає"
DBM_CORE_AUTO_YELL_OPTION_TEXT.shortfade 	= "Кричати (зі зворотним відліком), коли $spell:%s з вас спадає"
DBM_CORE_AUTO_YELL_OPTION_TEXT.iconfade 	= "Кричати (зі зворотним відліком і міткою), коли $spell:%s з вас спадає"
DBM_CORE_AUTO_YELL_OPTION_TEXT.position		= "Кричати (з міткою), коли на вас $spell:%s"
DBM_CORE_AUTO_YELL_OPTION_TEXT.combo 		= "Кричати (з індивідуальним текстом), коли на вас одночасно впливає $spell:%s та інші заклинання"

DBM_CORE_AUTO_YELL_ANNOUNCE_TEXT.shortyell = "%s"
DBM_CORE_AUTO_YELL_ANNOUNCE_TEXT.yell = "%s на " .. UnitName("player") .. "!"
DBM_CORE_AUTO_YELL_ANNOUNCE_TEXT.yellhelp = "%s на мені! ДОПОМОГИТЕ!"
DBM_CORE_AUTO_YELL_ANNOUNCE_TEXT.yelldispel = "%s на мені! Диспел мені!"
DBM_CORE_AUTO_YELL_ANNOUNCE_TEXT.yellmoveaway = "%s на мені! ВІДІЙДИ ВІД МЕНЕ!"
DBM_CORE_AUTO_YELL_ANNOUNCE_TEXT.count = "%s на " .. UnitName("player") .. "! (%%d)"
DBM_CORE_AUTO_YELL_ANNOUNCE_TEXT.fade = "%s спадає через %%d!"
DBM_CORE_AUTO_YELL_ANNOUNCE_TEXT.fademoveaway = "%s спадає через %%d! ВІДІЙДИ ВІД МЕНЕ!"
DBM_CORE_AUTO_YELL_ANNOUNCE_TEXT.shortfade = "%%d"
DBM_CORE_AUTO_YELL_ANNOUNCE_TEXT.iconfade = "{rt%%%2$d}%%%1$d"
DBM_CORE_AUTO_YELL_ANNOUNCE_TEXT.position = "%s %%s на {rt%%d}" .. UnitName("player") .. "{rt%%d}"
DBM_CORE_AUTO_YELL_ANNOUNCE_TEXT.combo = "%s і %%s"

--DBM_CORE_AUTO_YELL_CUSTOM_POSITION		= "{rt%d}%s{rt%d}"--Doesn't need translating. Has no strings
--DBM_CORE_AUTO_YELL_CUSTOM_POSITION2		= "{rt%d}{rt%d}%s{rt%d}{rt%d}"--Doesn't need translating. Has no strings
DBM_CORE_AUTO_YELL_CUSTOM_FADE 				= "%s зникає"
DBM_CORE_AUTO_HUD_OPTION_TEXT 				= "Показувати HudMap для $spell:%s"
DBM_CORE_AUTO_HUD_OPTION_TEXT_MULTI 		= "Показувати HudMap для різних механік"
DBM_CORE_AUTO_NAMEPLATE_OPTION_TEXT 		= "Показувати таблички з іконками аур для $spell:%s"
DBM_CORE_AUTO_RANGE_OPTION_TEXT 			= "Показувати вікно перевірки дистанції (%s м) для $spell:%s"--рядок, що використовується для range, щоб ми могли використовувати речі на кшталт "5/2" як значення для цього поля
DBM_CORE_AUTO_RANGE_OPTION_TEXT_SHORT 		= "Показувати вікно перевірки дистанції (%s м)"--для того, щоб фрейм діапазону використовувався не лише для однієї речі.
DBM_CORE_AUTO_RRRANGE_OPTION_TEXT 			= "Показувати зворотне вікно перевірки дистанції (%s) для $spell:%s"--Реверсний фрейм діапазону (зелений, якщо гравці в зоні досяжності, червоний, якщо ні)
DBM_CORE_AUTO_RRRANGE_OPTION_TEXT_SHORT 	= "Показувати зворотне вікно перевірки дистанції (%s)"
DBM_CORE_AUTO_INFO_FRAME_OPTION_TEXT 		= "Інформаційне вікно для $spell:%s"
DBM_CORE_AUTO_INFO_FRAME_OPTION_TEXT2 		= "Показувати інформаційне вікно для огляду бою"
DBM_CORE_AUTO_READY_CHECK_OPTION_TEXT 		= "Програвати звук перевірки готовності, коли кулять боса (навіть якщо він не є ціллю)"

-- New special warnings
DBM_CORE_MOVE_WARNING_BAR 				= "Індикатор попередження"
DBM_CORE_MOVE_WARNING_MESSAGE 			= "Дякуємо за використання DBM Right Version" --Dungeon Boss Master
DBM_CORE_MOVE_SPECIAL_WARNING_BAR 		= "Індикатор спец-попередження"
DBM_CORE_MOVE_SPECIAL_WARNING_TEXT 		= "Спеціальне попередження"

DBM_CORE_HUD_INVALID_TYPE 				= "Задано невірний тип HUD"
DBM_CORE_HUD_INVALID_TARGET 			= "Не задано коректну ціль для HUD"
DBM_CORE_HUD_INVALID_SELF 				= "Не можна використовувати себе як ціль для HUD"
DBM_CORE_HUD_INVALID_ICON 				= "Тип icon не може бути використаний на цілі без мітки"
DBM_CORE_HUD_SUCCESS 					= "HUD запущено з вашими параметрами. Він буде відключений через %s, або за допомогою '/dbm hud hide'."
DBM_CORE_HUD_USAGE	= {
	"Використання DBM-HudMap:",
	"-----------------",
	"/dbm hud <тип> <ціль> <тривалість> створює HUD, який вказує на гравця протягом бажаної тривалості",
	"Можливі типи: red, blue, green, yellow, icon (потрібна ціль із рейдовою міткою)",
	"Можливі цілі: target, focus, <ім'я гравця>",
	"Тривалість: будь-яке число (у секундах). Якщо не задано, то використовується 20 хв.",
	"/dbm hud hide відключає і приховує HUD"
}

DBM_ARROW_MOVABLE 			= "Індикатор стрілки"
DBM_ARROW_WAY_USAGE 		= "/dway <x> <y>: Створює стрілку, що вказує на певне місце (з використанням координат карти місцевої зони)"
DBM_ARROW_WAY_SUCCESS 		= "Щоб приховати стрілку, напишіть команду \"dbm arrow hide\" або дотягніться до неї"
DBM_ARROW_ERROR_USAGE	= {
	"Використання DBM-Arrow:",
	"-----------------",
	"/dbm arrow <x> <y>: створює стрілку, що вказує в певну точку (використовуючи координати світу)",
	"/dbm arrow map <x> <y>: створює стрілку, що вказує в певну точку (використовуючи координати зони)",
	"/dbm arrow <player>: створює стрілку, що вказує на певного гравця у вашій групі або рейді (регістрозалежно!)",
	"/dbm arrow hide: приховує стрілку",
	"/dbm arrow move: дозволяє переміщення стрілки"
}

DBM_SPEED_KILL_TIMER_TEXT 		= "Рекордна перемога"
DBM_SPEED_CLEAR_TIMER_TEXT 		= "Найкраще проходження"
DBM_COMBAT_RES_TIMER_TEXT 		= "Слід. заряд БР"
DBM_CORE_TIMER_RESPAWN 			= "Поява %s"


DBM_REQ_INSTANCE_ID_PERMISSION 		= "%s запитує дозвіл на перегляд ваших поточних збережень підземель.\nВи хочете надати %s таке право? Цей гравець отримає можливість запитувати цю інформацію без повідомлення протягом вашої поточної ігрової сесії."
DBM_ERROR_NO_RAID 					= "Ви повинні перебувати в рейдовій групі для використання цієї функції."
DBM_INSTANCE_INFO_REQUESTED 		= "Надіслано запит на перегляд поточних збережень підземель у членів рейду.\nЗверніть увагу, що гравці будуть повідомлені про це і можуть відхилити ваш запит."
DBM_INSTANCE_INFO_STATUS_UPDATE 	= "На запит відповіли %d гравців із %d користувачів DBM: %d надіслали дані, %d відхилили запит. Очікування відповіді продовжено на %d секунд..."
DBM_INSTANCE_INFO_ALL_RESPONSES 	= "Отримано відповідь від усіх членів рейду"
DBM_INSTANCE_INFO_DETAIL_DEBUG 		= "Гравець: %s ТипРезультату: %s Інстанс: %s ID: %s Складність: %d Розмір: %d Прогрес: %s"
DBM_INSTANCE_INFO_DETAIL_HEADER 	= "%s, складність %s:"
DBM_INSTANCE_INFO_DETAIL_INSTANCE 	= "    ID %s, прогрес %d: %s"
DBM_INSTANCE_INFO_DETAIL_INSTANCE2 	= "    прогрес %d: %s"
DBM_INSTANCE_INFO_NOLOCKOUT 		= "Ваша рейдова група не має збережень підземель."
DBM_INSTANCE_INFO_STATS_DENIED 		= "Відхилили запит: %s"
DBM_INSTANCE_INFO_STATS_AWAY 		= "Відійшли від комп'ютера: %s"
DBM_INSTANCE_INFO_STATS_NO_RESPONSE = "Встановлено застарілу версію DBM: %s"
DBM_INSTANCE_INFO_RESULTS 			= "Результати сканування збережень. Зверніть увагу, що інстанси можуть з'являтися більше одного разу, якщо у вашому рейді є гравці з локалізованими клієнтами WoW."
--DBM_INSTANCE_INFO_SHOW_RESULTS 	= "Не всі гравці ще відповіли: %s\n|HDBM:showRaidIdResults|h|cff3588ff[Показати поточні результати]|r|h"
DBM_INSTANCE_INFO_SHOW_RESULTS 		= "Не всі гравці ще відповіли: %s"

DBM_CORE_LAG_CHECKING 				= "Перевірка затримки у рейду..."
DBM_CORE_LAG_HEADER 				= "Dungeon Boss Master - Результати перевірки затримки"
DBM_CORE_LAG_ENTRY 					= "%s: глобальна затримка [%d ms] / локальна затримка [%d ms]"
DBM_CORE_LAG_FOOTER 				= "Немає відповіді: %s"

DBM_CORE_DUR_CHECKING 				= "Перевірка міцності рейду..."
DBM_CORE_DUR_HEADER 				= "Dungeon Boss Master - результати міцності"
DBM_CORE_DUR_ENTRY 					= "%s: міцність [%d відсоток] / зламано речей [%s]"
DBM_CORE_LAG_FOOTER 				= "Немає відповіді: %s"
